config/routes.rb
Rails.application.routes.draw do

  resources :items
  root 'items#new'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/valentine.rb
class Valentine < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    params[:item][:sentence_id] = rand(1..4)
    @item = Item.new(items_params)
    if @item.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  private

  def items_params
    params.require(:item).permit!
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= form_for(@item, html: {class: "form-horizontal"}) do |f| %>
    <%- Item.column_names.reject { |c| c.in? ['id', 'created_at', 'updated_at', 'sentence_id'] }.each do |field| %>
        <div class="form-group">
          <label class="control-label col-md-2">
            <%= f.label field, field.to_s.titleize %>
          </label>
          <div class="form-controls col-md-4">
            <%= f.text_field field, class: 'form-control' %>
          </div>
        </div>
    <%- end %>

    <div class="form-group">
      <div class="actions">
        <div class="col-md-offset-2 col-md-4">
          <%= f.submit 'Find Items for Sale', class: 'btn-create' %>
        </div>
      </div>
    </div>
<% end %>

app/views/items/_sentence1.html.erb
<p>Please <%= item.verb_one %> over here and rid me of this Gold's Gym Elliptical Machine. I got it a year ago from a friend who had only used it as a <%= item.noun_two %> rack. "That won't be me," I said, "I'll definitely stop eating croissants and use it," I swore. My <%= item.adjective_one %> roommate laughed and my friends made bets about the amount of times I'd actually step on it. Unfortunately, those <%= item.adjective_two %> punks were all right. Staring at it just reminds me of my lack of ambition, and it's also <%= item.verb_two %> up valuable space where I'd like to put a big beautiful white desk. The kind of furniture that not only allows me to feel good about my sedentary lifestyle, but actually encourages it under the guise of scholarly betterment.</p>
<p>The price is freakishly low at $<%= item.number %>.00, which I figure is just about enough to cover a pizza party for my roommates and me. But the sweetest part will be going to bed, my stomach achingly full of Crispy Basil's cuban specialty pizza, and not being mocked by the unforgiving atrocity taking up half my bedroom.</p>
<p>I also added a photo of my cat, <%= item.name %>, because he's dope.</p>

app/views/items/_sentence2.html.erb
<p>I woke up this morning and turned on the <%= item.noun_one %>.  I then <%= item.verb_one %> to the kitchen and fired up the <%= item.noun_two %>.
  The <%= item.adjective_one %> blue flame of the stove warmed my <%= item.adjective_two %> heart.  I then started to <%= item.verb_two %> my favorite morning breakfast, a croissant.</p>
<p>Even though I spent so much time cooking it I couldn’t finish my breakfast.  This is where you come in.  For the low price of $<%= item.number %>.00, You, can buy your very own, half eaten, <%= item.name %> croissant.  Made fresh this morning.</p>

app/views/items/_sentence3.html.erb
<p>This <%= item.noun_one %> is for totally for <%= item.noun_two %> and it's <%= item.adjective_one %>.</p>
<p><%= item.adjective_two %> buy! now  <%= item.verb_two %></p>
<p> $<%= item.number %>.00.</p>

app/views/items/_sentence4.html.erb
<p>For Sale: $<%= item.number %>.00</p>
<p>I got a <%= item.noun_one %> a while back, I was trying to be more a <%= item.adjective_one %> <%= item.noun_two %> but its not <%= item.verb_one %>, and I need to give it away to a good home as soon as possible. Message my <%= item.adjective_two %> <%= item.noun_two %> you feel at all like <%= item.verb_two %>.

app/views/items/index.html.erb
<div class="page-header">
  <h1>All Items for sale</h1>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @items.each do |item| %>
  <tr>
    <td>
      <%= render partial: "sentence#{item.sentence_id || 1}", locals: { item: item } %>
    </td>
  </tr>
    <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<div class="page-header">
  <h3>Fill out the form below to find items for sale.</h3>
  </div>
<%= render 'form' %>

app/views/items/show.html.erb
<div class="page-header">
  <h1>Item for Sale: $<%= @item.number %></h1>
</div>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <%= render partial: "sentence#{@item.sentence_id || 1}", locals: { item: @item } %>
  </div>
  <div class="col-md-4"></div>
</div>
<br>
<br>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4"><%= link_to "See all Items for Sale", items_path, :class => 'btn-create' %></div>
  <div class="col-md-4"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Croissant.ForSale</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_url %>">Croissant.ForSale</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
    </div>
    <!--/.navbar-collapse -->
  </div>
</nav>

<div class="container">

  <%= yield %>
  
  <footer>
    <%= link_to "Home", root_path %>
  </footer>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>

</body>
</html>